import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/index.css";
import { Header } from "@/components/Header";
import Script from "next/script";

const inter = Inter({
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Laguntza Fisioterapia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <main className="main-content">{children}</main>
      </body>
      <Script src="/scripts/navigation-scroll.js" />
    </html>
  );
}
