import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/index.css";
import { Header } from "@/components/Header";
import Script from "next/script";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

 
export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export const metadata: Metadata = {
  title: "Laguntza Fisioterapia",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  // Enable static rendering
  setRequestLocale(locale);

  return (
    <html lang={locale}>
      <body className={`${inter.className}`}>
        <NextIntlClientProvider>
          <Header />
          <main className="main-content">{children}</main>
        </NextIntlClientProvider>
      </body>
      <Script src="/scripts/navigation-scroll.js" />
    </html>
  );
}
